services:
  heathrow-demo:
    build: ./frontend
    container_name: heathrow-demo
    ports:
      - "8030:80"
    depends_on:
      - heathrow-demo-backend
    restart: unless-stopped

  heathrow-demo-backend:
    build: ./backend
    container_name: heathrow-demo-backend
    restart: unless-stopped
